# Set board public name
CONFIG_ZMK_KEYBOARD_NAME="Ilya's Lily58"

# Increase debounce time to prevent chatter
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable virtual mouse
CONFIG_ZMK_POINTING=y

# Enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_WIDGET_LAYER_STATUS=n

# Enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Bluetooth settings
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Combo settings
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=4

# Set sleep timeout to 30min (30*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Other
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_ZMK_IDLE_TIMEOUT=10000

