# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment to enable virtual mouse
CONFIG_ZMK_POINTING=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Bluetooth settings
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Combo settings
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=4

# Set sleep timeout to 30min (30*60*1000ms)
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Other
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_ZMK_IDLE_TIMEOUT=10000

